name: TypeScript Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build(prod)
        run: pnpm run build:prod
        env:
          NODE_ENV: production

      - name: Check if build succeeded
        run: |
          if [ -f "./dist/main.js" ]; then
            echo "Build succeeded! Output file exists."
          else
            echo "Build failed! Output file does not exist."
            exit 1
          fi